# Generated by Django 5.1.3 on 2024-11-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagamodel',
            name='descricao',
            field=models.CharField(default='', max_length=255, verbose_name='Descrição da Vaga'),
        ),
        migrations.AddField(
            model_name='vagamodel',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email da Empresa'),
        ),
    ]
